name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Tests
      run: go test
